[project]
authors = ["Huite <huite.bootsma@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "deltaforge"
platforms = ["win-64"]
version = "0.0.1"

[dependencies]
python = "3.12.*"
humanize = "*"

[tasks]
# Make sure you have pixi-pack installed and Inno Setup.
lockfile = "pixi update"
pack = { cmd = "pixi-pack pack --output-file deltaforge.tar", depends-on = ["lockfile"] }
create = { cmd = "iscc installer.iss", depends-on = ["pack"] }